
variables:
    CONAN_USERNAME: "arsen-studio"
    CONAN_REFERENCE: "openvr/master"
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD: "https://api.bintray.com/conan/arsen-studio/arsen-deps"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: "1"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools
        - conan user
    script:
        - python build.py

gcc-4.9:
    image: lasote/conangcc49
    variables:
        CONAN_GCC_VERSIONS: "4.9"
    <<: *build-template

gcc-5:
    image: lasote/conangcc5
    variables:
        CONAN_GCC_VERSIONS: "5"
    <<: *build-template

gcc-6:
    image: lasote/conangcc6
    variables:
        CONAN_GCC_VERSIONS: "6"
    <<: *build-template

gcc-7:
    image: lasote/conangcc7
    variables:
        CONAN_GCC_VERSIONS: "7"
    <<: *build-template

clang-3.9:
    image: lasote/conanclang39
    variables:
        CONAN_CLANG_VERSIONS: "3.9"
    <<: *build-template

clang-4.0:
    image: lasote/conanclang40
    variables:
        CONAN_CLANG_VERSIONS: "4.0"
    <<: *build-template

clang-5.0:
    image: lasote/conanclang50
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
    <<: *build-template

clang-6.0:
    image: buildpack-deps:stretch
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
    <<: *build-template
    before_script:
        - curl -sL http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        - echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main" > /etc/apt/sources.list.d/llvm.list
        - apt-get update -yqq
        - apt-get install clang-6.0 libc++-dev python-dev python-pip git cmake -yqq
        - ln -s /usr/bin/clang-6.0 /usr/bin/clang
        - ln -s /usr/bin/clang++-6.0 /usr/bin/clang++
        - pip install conan conan_package_tools
